// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Node's raw ESM loader can't resolve the generated Prisma client's
    // `.js`-extension specifiers against `.ts` sources, so the seed script
    // (src/prisma-seed/seed.ts) is built through the normal tsc build first.
    seed: "npm run build && node dist/prisma-seed/seed.js",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
